version: '3.8'

services:
  apache:
    build:
      context: ./docker/apache
    container_name: api_apache
    ports:
      - "82:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
    networks:
      - api_network

  mysql:
    image: mysql:5.7
    container_name: api_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - "3308:3306"
    networks:
      - api_network

networks:
  api_network:
    name: api_network
    driver: bridge